config/routes.rb
Rails.application.routes.draw do
  get '/todos/list', as: 'list_todo'
  get '/todos', to: 'todos#index'
  get 'todos/new', as: 'new_todo'
  post '/todos', to: 'todos#create'
  get '/todos/:id', to: 'todos#show', as: 'todo'
  get '/todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch '/todos/:id', to: 'todos#update'
  delete '/todos/:id', to: 'todos#destroy'
  get '/todos/:id/complete', to: 'todos#complete', as: 'complete_todo'
  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.completed = false
    @todo.save
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
    @todo.completed = false
    @todo.save
  end

  def update
    @todo = Todo.find(params[:id])
    redirect_to todos_path if @todo.update(todo_params)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">        
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- ********* -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_navbar.html.erb
<nav class='navbar navbar-expand navbar-dark bg-dark fixed-top'>
  <div class='collapse navbar-collapse ' id='navbarNav'>
    <ul class='navbar-nav'>
      <li class='nav-item'>
        <a class='navbar-brand' href='<%= root_path %>'> INICIO </a>
      </li>
      <li class='nav-item'>
        <a class='nav-link' href='<%= list_todo_path %>'> Lista </a>
      </li>
      <li class='nav-item'>
        <a class='nav-link' href='<%= new_todo_path %>'> Nuevo </a>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<div class='row'>
  <div class='col-md-6 offset-md-3 MT'>
    <div class="card card-body bg-dark">
      <%= form_with model: @todo, local: true do |form| %>
        <%= form.text_area :description %>
        <%= form.submit class:"btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<div class='row'>
  <div class='col-md-6 offset-md-3'>
      <%= link_to 'Crear', new_todo_path, class: 'btn btn-info card card-body bg-success text-dark MB MT' %>
      <% @todos.each do |t| %>
        <div class='card card-body bg-dark MB'>
          <div class='list-group-item text-center'>
            <p> <%= t.description %> </p>
          </div>
          <%= link_to 'Ver', todo_path(t), class: 'btn btn-info' %>
          <%= link_to 'Editar', edit_todo_path(t), class: 'btn btn-warning' %>
          <%= link_to 'Borrar', todo_path(t), method: :delete, class: 'btn btn-danger' %>
          <% if t.completed == false %>
            <%= link_to 'Completar', complete_todo_path(t), class: 'btn btn-secondary' %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/todos/list.html.erb
<div class='row'>
  <div class='col-md-4 offset-md-1 MT'>
    <ul class='card card-body bg-dark'>
    <h4 class='text-success'> Completados </h4>
      <% @todos.each do |t| %>
        <% if t.completed == true %>
          <div class='list-group-item text-center'>
            <p> <%= t.description %> </p>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class='col-md-4 offset-md-2 MT'>
    <ul class='card card-body bg-dark'>
  <h4 class='text-danger'> NO Completados </h4>
      <% @todos.each do |t| %>
        <% if t.completed == false %>
          <div class='list-group-item text-center'>
            <p> <%= t.description %> </p>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/todos/new.html.erb
<div class='row'>
  <div class='col-md-6 offset-md-3 MT'>
    <div class="card card-body bg-dark">
      <%= form_with model: @todo, local: true do |f| %>
        <%= f.text_area :description %>
        <%= f.submit class:'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<div class='row'>
  <div class='col-md-6 offset-md-3 MT'>
    <div class='card card-body bg-light text-center'>
      <%= @todo.description %>
      <%= link_to 'Editar', edit_todo_path, class: 'btn btn-warning MT' %>
      <%= link_to 'Borrar', todo_path, method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>